name: franck_ehrhart
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # dependencies for navigation
  google_nav_bar: ^3.0.0


  # dependencies for business card
  url_launcher: ^5.5.0

  # dependencies for icons
  flutter_icons: ^1.1.0

  # dependencies for pictures from camera
  camera: ^0.5.8+5
  path_provider: ^1.6.14
  path: ^1.7.0
  esys_flutter_share: ^1.0.2

# dependencies for geolocalisator
  geolocator: ^5.3.2+2
  geocoder: ^0.2.1

  # dependencies for screenshot
  screenshot: ^0.1.1
  image_picker_saver: ^0.3.0

  # dependencies for compass
  flutter_compass: ^0.4.3
  permission_handler: ^3.2.2

  # dependencies for maps
  google_maps_flutter: ^0.5.24+1
  location: ^2.5.0
  fluttertoast: ^3.1.3

  # dependencies for transitions/navigation
  page_transition: ^1.1.6
  curved_navigation_bar: ^0.3.4

  # dependencies for webviews
  webview_flutter: ^0.3.22+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: ^0.7.3
  flutter_rename_app: ^1.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_rename_app:
  application_name: Franck Ehrhart
  dart_package_name: franck_ehrhart
  application_id: fr.remax.franckehrhart
  bundle_id: fr.remax.franckehrhart

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
